<?php

namespace App\Models;

use CodeIgniter\Model;

class CurriculoLattesModel extends Model
{
    protected $table = 'curriculos_lattes';
    protected $primaryKey = 'id_lattes';
    protected $useAutoIncrement = false;
    protected $returnType = 'array';
    protected $useTimestamps = false;
    protected $protectFields = true;

    // O ID deve ser informado como string para preservar os zeros a esquerda.
    protected $allowedFields = [
        'id_lattes',
        'nome',
        'atualizacao_cv',
        'nascimento',
        'nacionalidade',
        'nome_em_citacoes',
        'graduacao',
        'especializacao',
        'mestrado',
        'doutorado',
        'pos_doutorado',
        'livre_docencia',
        'end_prof_instituicao',
        'end_prof_orgao',
        'end_prof_unidade',
        'end_prof_pais',
        'end_prof_uf',
        'end_prof_cidade',
        'primeira_grande_area',
        'primeira_area',
        'cursos_curta_duracao_formacao',
        'cursos_extensao',
        'mba',
        'outros_cursos',
        'direcao_administracao',
        'linhas_pesquisa',
        'atividades_ensino',
        'atividades_extensao',
        'conselhos_comissoes_consultorias',
        'estagios',
        'servicos_tecnicos',
        'treinamentos_ministrados',
        'outras_atividades_tecnico_cientificas',
        'membro_corpo_editorial',
        'membro_comite_assessoramento',
        'revisor_periodico',
        'revisor_projeto_agencia_fomento',
        'artigos_periodicos',
        'artigos_eventos',
        'resumos_expandidos',
        'resumos',
        'livros_completos',
        'livros_organizados',
        'capitulos_livros',
        'artigos_aceitos',
        'textos_jornais_revistas',
        'apresentacao_trabalhos',
        'partituras',
        'traducoes',
        'prefacios_posfacios',
        'outras_producoes_bibliograficas',
        'softwares_sem_patente',
        'produtos',
        'processos',
        'trabalhos_tecnicos',
        'cartas_mapas',
        'cursos_curta_duracao_producao',
        'material_didatico',
        'editoracao',
        'manutencao_obra_artistica',
        'maquetes',
        'entrevistas_programas_midia',
        'relatorios_pesquisa',
        'websites_blogs',
        'outras_producoes_tecnicas',
        'artes_cenicas',
        'musicas',
        'artes_visuais',
        'outras_producoes_artisticas',
        'patentes',
        'softwares_com_patente',
        'marcas',
        'cultivar_protegida',
        'cultivar_registrada',
        'desenhos',
        'topografias',
        'supervisoes_pos_doutorado',
        'orientacoes_doutorado_principal',
        'orientacoes_doutorado_coorientador',
        'orientacoes_mestrado_principal',
        'orientacoes_mestrado_coorientador',
        'orientacoes_tcc',
        'orientacoes_ic',
        'orientacoes_especializacao',
        'orientacoes_outra_natureza',
        'supervisoes_pos_doutorado_andamento',
        'orientacoes_doutorado_andamento_principal',
        'orientacoes_doutorado_andamento_coorientador',
        'orientacoes_mestrado_andamento_principal',
        'orientacoes_mestrado_andamento_coorientador',
        'orientacoes_tcc_andamento',
        'orientacoes_ic_andamento',
        'orientacoes_especializacao_andamento',
        'orientacoes_outra_natureza_andamento',
        'bancas_tcc',
        'bancas_especializacao',
        'bancas_qualificacao_mestrado',
        'bancas_qualificacao_doutorado',
        'bancas_mestrado',
        'bancas_doutorado',
        'bancas_livre_docencia',
        'bancas_concurso',
        'outras_bancas',
        'projetos_pesquisa',
        'projetos_extensao',
        'projetos_ensino',
        'projetos_desenvolvimento',
        'projetos_outros',
        'premios_titulos',
        'participacao_congressos',
        'participacao_seminarios',
        'participacao_simposios',
        'participacao_oficinas',
        'participacao_encontros',
        'participacao_feiras',
        'participacao_exposicoes',
        'participacao_olimpiadas',
        'participacao_outros_eventos',
        'organizacao_eventos',
    ];
}

